### ISSUE TITLE
Default object store, fails if you try to write something to it

### ISSUE THREAD

**Issue by asequeira** [mulesoft/mule-module-objectstore#10]
This was open by Ross in [Mule CE JIRA](http://www.mulesoft.org/jira/browse/MULE-6820):

simply create a new store with:

    <objectstore:config name="defaultStore" doc:name="ObjectStore"/>

Try and store a new key in it and get the following:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
ERROR 2013-05-06 17:09:49,894 [[sms-broadcast].connector.http.mule.default.receiver.03] org.mule.exception.DefaultMessagingExceptionStrategy: 
******************************************************************************** 
Message : /projects/workspace-34/.mule/.mule/sms-broadcast/objectstore/DEFAULT_PARTITION/numbers.obj (No such file or directory) (java.io.FileNotFoundException) 
Type : org.mule.api.store.ObjectDoesNotExistException 
Code : MULE_ERROR--2 
JavaDoc : http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/store/ObjectDoesNotExistException.html 
******************************************************************************** 
Exception stack is: 
1. /projects/workspace-34/.mule/.mule/sms-broadcast/objectstore/DEFAULT_PARTITION/numbers.obj (No such file or directory) (java.io.FileNotFoundException) 
  java.io.FileInputStream:-2 (null) 
2. /projects/workspace-34/.mule/.mule/sms-broadcast/objectstore/DEFAULT_PARTITION/numbers.obj (No such file or directory) (java.io.FileNotFoundException) (org.mule.api.store.ObjectDoesNotExistException) 
  org.mule.util.store.PartitionedPersistentObjectStore:339 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/store/ObjectDoesNotExistException.html) 
******************************************************************************** 
Root Exception stack trace: 
java.io.FileNotFoundException: /projects/workspace-34/.mule/.mule/sms-broadcast/objectstore/DEFAULT_PARTITION/numbers.obj (No such file or directory) 
at java.io.FileInputStream.open(Native Method) 
at java.io.FileInputStream.<init>(FileInputStream.java:120) 
at org.mule.util.store.PartitionedPersistentObjectStore.deserialize(PartitionedPersistentObjectStore.java:329) 
at org.mule.util.store.PartitionedPersistentObjectStore.retrieve(PartitionedPersistentObjectStore.java:112) 
at org.mule.util.store.AbstractPartitionedObjectStore.retrieve(AbstractPartitionedObjectStore.java:61) 
at StoreNumbers.storeNumber(StoreNumbers.java:19) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) 
at java.lang.reflect.Method.invoke(Method.java:597) 
at org.mule.model.resolvers.AbstractEntryPointResolver.invokeMethod(AbstractEntryPointResolver.java:151) 
at org.mule.impl.model.resolvers.AnnotatedEntryPointResolver.invoke(AnnotatedEntryPointResolver.java:141) 
at org.mule.model.resolvers.DefaultEntryPointResolverSet.invoke(DefaultEntryPointResolverSet.java:39) 
at org.mule.component.DefaultComponentLifecycleAdapter.invoke(DefaultComponentLifecycleAdapter.java:343) 
at org.mule.component.AbstractJavaComponent.invokeComponentInstance(AbstractJavaComponent.java:86) 
at org.mule.component.AbstractJavaComponent.doInvoke(AbstractJavaComponent.java:77) 
at org.mule.component.AbstractComponent.invokeInternal(AbstractComponent.java:126) 
at org.mule.component.AbstractComponent.access$000(AbstractComponent.java:61) 
at org.mule.component.AbstractComponent$1$1.process(AbstractComponent.java:242) 
at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27) 
at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61) 
at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47) 
at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27) 
at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61) 
at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47) 
at org.mule.component.AbstractComponent.process(AbstractComponent.java:160) 
at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27) 
at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61) 
at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47) 
at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27) 
at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47) 
at org.mule.processor.AsyncInterceptingMessageProcessor.process(AsyncInterceptingMessageProcessor.java:101) 
at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27) 
at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61) 
at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47) 
at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27) 
at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47) 
at org.mule.interceptor.AbstractEnvelopeInterceptor.process(AbstractEnvelopeInterceptor.java:55) 
at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27) 
at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61) 
at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47) 
at org.mule.processor.AbstractFilteringMessageProcessor.process(AbstractFilteringMessageProcessor.java:44) 
at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27) 
at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61) 
at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47) 
at org.mule.const...

**Comment by tejaswip** [comment]
The issue cannot be replicates so I am closing this issue. I was able to create and use the object store as described above. The following is the flow I have used.

    <http:listener-config name="HTTP_Listener_Configuration" host="0.0.0.0" port="8081" doc:name="HTTP Listener Configuration"/>
    <objectstore:config name="defaultStore" doc:name="ObjectStore"/>
    <flow name="testFlow">
        <http:listener config-ref="HTTP_Listener_Configuration" path="/test" doc:name="HTTP"/>
        <objectstore:store config-ref="defaultStore" key="test" value-ref="#[string:test]" doc:name="ObjectStore"/>
        <logger message="Invoking retrieve" level="INFO" doc:name="Logger"/>
        <objectstore:retrieve config-ref="defaultStore" key="test" doc:name="ObjectStore"/>
        <logger message="Retrieved value is #[payload]" level="INFO" doc:name="Logger"/>
    </flow>
